data_shape: [8, 48, 84, 4] # (n_bars, n_timesteps, n_pitches, n_tracks)
beat_resolution: 12 # number of time steps used to represent a beat
latent_dim: 128
ylatent_dim: 3
is_conditional: true
is_accompaniment: false
condition_track_idx: ~
use_binary_neurons: false
nets:
  generator: default
  discriminator: default
